// Package indexgen regenerates the single-surface knowledge index
// (knowledge-base/knowledge/index.md) from a pure filesystem pass — no DB, no
// LLM. Sections are emitted in tier-priority order (Knowledge, Projects,
// Daily, Deep Thoughts) so budgeted truncation for session-start injection
// cuts the raw-capture tiers first.
package indexgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"silo.local/silo-kb/internal/vault"
)

const Marker = "<!-- GENERATED by silo-kb sync-index — do not hand-edit. Run /kb-sync-index to regenerate. -->"

// Generate builds the full index content from the vault.
func Generate(vaultRoot string) (string, error) {
	notes, err := vault.Walk(vaultRoot)
	if err != nil {
		return "", err
	}

	byTier := map[vault.Tier][]*vault.Note{}
	for _, n := range notes {
		byTier[n.Tier] = append(byTier[n.Tier], n)
	}
	for _, ns := range byTier {
		sort.Slice(ns, func(i, j int) bool { return ns[i].Path < ns[j].Path })
	}

	var b strings.Builder
	b.WriteString(Marker + "\n\n# Knowledge Index\n")

	section := func(title string, ns []*vault.Note, line func(*vault.Note) string) {
		if len(ns) == 0 {
			return
		}
		fmt.Fprintf(&b, "\n## %s\n\n", title)
		for _, n := range ns {
			b.WriteString(line(n) + "\n")
		}
	}

	section("Knowledge", byTier[vault.TierKnowledge], knowledgeLine)
	section("Projects", byTier[vault.TierProject], projectLine)
	section("Daily", byTier[vault.TierDaily], dailyLine)
	section("Deep Thoughts", byTier[vault.TierDeepThought], func(n *vault.Note) string {
		return fmt.Sprintf("- [[%s]] `deep-thought`", wikiname(n.Path))
	})
	return b.String(), nil
}

// Write atomically replaces knowledge/index.md.
func Write(vaultRoot string) error {
	content, err := Generate(vaultRoot)
	if err != nil {
		return err
	}
	dest := filepath.Join(vaultRoot, "knowledge/index.md")
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, []byte(content+"\n"), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

// Truncate cuts the generated index to a character budget by dropping whole
// lines from the end — tier-priority ordering means daily/deep-thought entries
// go first, knowledge/projects entries survive.
func Truncate(content string, budget int) string {
	if budget <= 0 || len(content) <= budget {
		return content
	}
	lines := strings.Split(content, "\n")
	total := len(content)
	cut := len(lines)
	for cut > 0 && total > budget {
		cut--
		total -= len(lines[cut]) + 1
	}
	out := strings.TrimRight(strings.Join(lines[:cut], "\n"), "\n")
	return out + "\n\n_[index truncated to fit context budget]_"
}

func knowledgeLine(n *vault.Note) string {
	name := wikiname(n.Path)
	if strings.HasPrefix(n.Path, "knowledge/archive/") {
		return fmt.Sprintf("- [[%s]] `%s` archived", name, n.Type())
	}
	maturity, _ := n.Frontmatter["maturity"].(string)
	conf := n.Frontmatter["confidence"]
	return fmt.Sprintf("- [[%s]] `%s` %s·%v", name, n.Type(), maturity, conf)
}

func projectLine(n *vault.Note) string {
	return fmt.Sprintf("- [[%s]] `%s` → %s", wikiname(n.Path), n.Type(), n.Path)
}

var checkboxRe = regexp.MustCompile(`(?m)^\s*- \[ \]`)

// dailyLine synthesizes a counts-only digest from the log's h2 category
// sections — a structural scan, no LLM. If a log stops being categorized the
// digest degrades to a bare entry count: that's the tell that the extractor's
// output format needs tightening.
func dailyLine(n *vault.Note) string {
	name := wikiname(n.Path)
	counts := categoryCounts(n.Body)
	unresolved := len(checkboxRe.FindAllString(n.Body, -1))

	var parts []string
	for _, c := range counts {
		if c.category == "Unresolved" {
			continue // counted via checkboxes instead
		}
		parts = append(parts, fmt.Sprintf("%d %s", c.items, strings.ToLower(c.category)))
	}
	if unresolved > 0 {
		parts = append(parts, fmt.Sprintf("%d unresolved", unresolved))
	}
	if len(parts) == 0 {
		return fmt.Sprintf("- [[%s]] `daily`", name)
	}
	return fmt.Sprintf("- [[%s]] `daily` — %s", name, strings.Join(parts, ", "))
}

type catCount struct {
	category string
	items    int
}

var h2Re = regexp.MustCompile(`(?m)^## (.+)$`)
var bulletRe = regexp.MustCompile(`(?m)^- `)

func categoryCounts(body string) []catCount {
	locs := h2Re.FindAllStringSubmatchIndex(body, -1)
	var out []catCount
	for i, loc := range locs {
		end := len(body)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		sectionBody := body[loc[1]:end]
		out = append(out, catCount{
			category: body[loc[2]:loc[3]],
			items:    len(bulletRe.FindAllString(sectionBody, -1)),
		})
	}
	return out
}

func wikiname(path string) string {
	return strings.TrimSuffix(filepath.Base(path), ".md")
}
