package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"silo.local/silo-kb/internal/vault"
)

func TestWriteCreatesFreshScaffold(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}
	vr := filepath.Join(root, "knowledge-base")

	// Every tier dir exists and carries a .gitkeep.
	for _, d := range tierDirs {
		if st, err := os.Stat(filepath.Join(vr, d)); err != nil || !st.IsDir() {
			t.Errorf("missing tier dir %q: %v", d, err)
		}
		if _, err := os.Stat(filepath.Join(vr, d, ".gitkeep")); err != nil {
			t.Errorf("missing .gitkeep in %q: %v", d, err)
		}
	}

	// The three reserved files exist with their expected leading content.
	wantHead := map[string]string{
		"index.md":           "---\nokf_version: \"0.1\"\n---",
		"knowledge/index.md": "<!-- GENERATED by silo-kb sync-index",
		"knowledge/log.md":   "<!-- Appended by silo-kb compile",
	}
	for rel, head := range wantHead {
		b, err := os.ReadFile(filepath.Join(vr, rel))
		if err != nil {
			t.Errorf("missing %q: %v", rel, err)
			continue
		}
		if !strings.HasPrefix(string(b), head) {
			t.Errorf("%q content = %q…, want prefix %q", rel, string(b[:min(len(b), 40)]), head)
		}
	}

	// The repo-root PROJECTS.md registry is written with its heading.
	if b, err := os.ReadFile(filepath.Join(root, "PROJECTS.md")); err != nil {
		t.Errorf("missing PROJECTS.md: %v", err)
	} else if !strings.HasPrefix(string(b), "# PROJECTS") {
		t.Errorf("PROJECTS.md content = %q…, want prefix %q", string(b[:min(len(b), 40)]), "# PROJECTS")
	}

	// The clean-slate invariant: a walk of the fresh scaffold yields no notes
	// (index.md/log.md are reserved and skipped).
	notes, err := vault.Walk(vr)
	if err != nil {
		t.Fatalf("vault.Walk: %v", err)
	}
	if len(notes) != 0 {
		t.Errorf("fresh scaffold walked %d notes, want 0", len(notes))
	}
}

// Write overwrites an existing populated PROJECTS.md — that is the reset.
func TestWriteResetsPopulatedProjects(t *testing.T) {
	root := t.TempDir()
	projects := filepath.Join(root, "PROJECTS.md")
	if err := os.WriteFile(projects, []byte("# PROJECTS\n\n| foo | bar | baz | qux |\n"), 0o644); err != nil {
		t.Fatalf("seed PROJECTS.md: %v", err)
	}
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}
	b, err := os.ReadFile(projects)
	if err != nil {
		t.Fatalf("read PROJECTS.md: %v", err)
	}
	if strings.Contains(string(b), "foo") {
		t.Errorf("PROJECTS.md still contains the seeded row after reset:\n%s", b)
	}
}
