package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"silo.local/silo-kb/internal/vault"
)

func TestWriteCreatesFreshScaffold(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}
	vr := filepath.Join(root, "knowledge-base")

	// Every tier dir exists and carries a .gitkeep.
	for _, d := range tierDirs {
		if st, err := os.Stat(filepath.Join(vr, d)); err != nil || !st.IsDir() {
			t.Errorf("missing tier dir %q: %v", d, err)
		}
		if _, err := os.Stat(filepath.Join(vr, d, ".gitkeep")); err != nil {
			t.Errorf("missing .gitkeep in %q: %v", d, err)
		}
	}

	// The three reserved files exist with their expected leading content.
	wantHead := map[string]string{
		"index.md":           "---\nokf_version: \"0.1\"\n---",
		"knowledge/index.md": "<!-- GENERATED by silo-kb sync-index",
		"knowledge/log.md":   "<!-- Appended by silo-kb compile",
	}
	for rel, head := range wantHead {
		b, err := os.ReadFile(filepath.Join(vr, rel))
		if err != nil {
			t.Errorf("missing %q: %v", rel, err)
			continue
		}
		if !strings.HasPrefix(string(b), head) {
			t.Errorf("%q content = %q…, want prefix %q", rel, string(b[:min(len(b), 40)]), head)
		}
	}

	// The clean-slate invariant: a walk of the fresh scaffold yields no notes
	// (index.md/log.md are reserved and skipped).
	notes, err := vault.Walk(vr)
	if err != nil {
		t.Fatalf("vault.Walk: %v", err)
	}
	if len(notes) != 0 {
		t.Errorf("fresh scaffold walked %d notes, want 0", len(notes))
	}
}
